name: Build and publish uantwerpen custom environments

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/uantwerpen.yml

  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./uantwerpen/containers/computer-graphics/Dockerfile
          push: true
          tags: |
            ghcr.io/uantwerpen/inginious/env-computer-graphics:latest
            ghcr.io/uantwerpen/inginious/env-computer-graphics:${{ github.sha }}
          build-args: |
            VERSION=main
            REGISTRY=ghcr.io